"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

#starting list
list = [1,2]

#generate the list of fibonnaci numbers
while (list[-1] <= 4000000):
	a = list[-1]
	b = list[-2]
	i = a + b
	list.append(i)
	
#store even values from fibonacci list
even_list = []
x = 0
while (list[x] <= 4000000):
	if list[x] % 2 == 0:
		even_list.append(list[x])
		x += 1
	else:
		x+=1
#sum all even numbers and print
print(sum(even_list))